"""Build publication-ready figures and tables for the paper.

Reads cached experiment CSVs only — never re-runs an experiment, never makes
a network call. Fails loudly if an expected input is missing.

Usage:
    python -m src.build_paper_assets
    python -m src.build_paper_assets --results-dir results --out reports/paper_assets

Outputs:
    reports/paper_assets/
        fig1_tokenization_parity_by_tokenizer.{png,pdf}
        table1_tokenization_audit_summary.{csv,md,tex}
        fig2_examples_fit_vs_budget.{png,pdf}
        table2_radical_token_sensitivity_summary.{csv,md,tex}
        fig3_tokenizer_adaptation_counterfactual.{png,pdf}
        appendix_table_fixed_context_full.{csv,md,tex}
        appendix_fig_accuracy_vs_budget.{png,pdf}
        appendix_table_perturbation_summary.{csv,md,tex}
        appendix_fig_perturbation_stability.{png,pdf}
        appendix_table_full_audit_with_controls.{csv,md,tex}
        captions.md
        README.md
"""

from __future__ import annotations

import math
from pathlib import Path

import click
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

from .plotting import apply_style, save_figure

# ----------------------------------------------------------------------
# Conventions
# ----------------------------------------------------------------------

# Display order for tokenizers (worst-parity-rightward narrative).
TOKENIZER_ORDER = [
    "char",
    "byte",
    "qwen25",
    "tiktoken_o200k",
    "llama3",
    "tiktoken_cl100k",
]

TOKENIZER_LABELS = {
    "char": "char",
    "byte": "byte",
    "qwen25": "Qwen 2.5",
    "tiktoken_o200k": "o200k_base",
    "llama3": "Llama 3",
    "tiktoken_cl100k": "cl100k_base",
}

TRANSFORM_LABELS = {
    "identity": "identity",
    "punct_ascii": "punct → ASCII",
    "punct_fullwidth": "punct → full-width",
    "to_simplified": "→ Simplified",
    "to_traditional": "→ Traditional",
    "numerals_arabic": "numerals → Arabic",
}

# Two distinct markers + linestyles so EN/ZH lines remain distinguishable in
# grayscale print without relying on hue alone.
LANG_STYLE = {
    "en": {"label": "English", "marker": "o", "linestyle": "-",  "color": "#1f77b4"},
    "zh": {"label": "Chinese", "marker": "s", "linestyle": "--", "color": "#d62728"},
}


# ----------------------------------------------------------------------
# Small helpers
# ----------------------------------------------------------------------

def _require_csv(path: Path) -> pd.DataFrame:
    if not path.exists():
        raise FileNotFoundError(
            f"Required cached input is missing: {path}\n"
            f"Run the corresponding experiment first (see README.md)."
        )
    if path.stat().st_size == 0:
        raise ValueError(f"Required cached input is empty: {path}")
    return pd.read_csv(path)


def _round(value: float, ndigits: int = 3) -> float:
    if value is None or (isinstance(value, float) and (math.isnan(value) or math.isinf(value))):
        return value
    return round(float(value), ndigits)


def _fmt_p(p: float) -> str:
    """Format p-values: two-decimal for >=0.001, scientific for tiny."""
    if p is None or (isinstance(p, float) and math.isnan(p)):
        return "n/a"
    p = float(p)
    if p >= 0.001:
        return f"{p:.3f}"
    return f"{p:.1e}"


def _fmt_ci(lo: float, hi: float, ndigits: int = 2) -> str:
    return f"[{lo:.{ndigits}f}, {hi:.{ndigits}f}]"


def _escape_tex(s: object) -> str:
    """Minimal LaTeX escaping for string cells in tabular bodies."""
    if s is None:
        return ""
    if isinstance(s, float) and math.isnan(s):
        return ""
    text = str(s)
    # Order matters: backslash first.
    repls = [
        ("\\", r"\textbackslash{}"),
        ("&", r"\&"),
        ("%", r"\%"),
        ("$", r"\$"),
        ("#", r"\#"),
        ("_", r"\_"),
        ("{", r"\{"),
        ("}", r"\}"),
        ("~", r"\textasciitilde{}"),
        ("^", r"\textasciicircum{}"),
    ]
    for a, b in repls:
        text = text.replace(a, b)
    return text


def _df_to_tex(df: pd.DataFrame, *, caption: str | None = None,
               label: str | None = None) -> str:
    """Render a DataFrame as a simple booktabs-style LaTeX tabular.

    Strings are escaped; numeric cells are passed through as their `str(...)`.
    Designed to be pasted into a paper inside a `table` environment.
    """
    cols = list(df.columns)
    align = "l" + "r" * (len(cols) - 1) if len(cols) > 1 else "l"
    lines: list[str] = []
    lines.append("% Auto-generated by src.build_paper_assets — do not hand-edit.")
    if caption is not None or label is not None:
        lines.append(r"\begin{table}[t]")
        lines.append(r"  \centering")
    lines.append(rf"\begin{{tabular}}{{{align}}}")
    lines.append(r"\toprule")
    lines.append(" & ".join(_escape_tex(c) for c in cols) + r" \\")
    lines.append(r"\midrule")
    for _, row in df.iterrows():
        cells = [_escape_tex(row[c]) for c in cols]
        lines.append(" & ".join(cells) + r" \\")
    lines.append(r"\bottomrule")
    lines.append(r"\end{tabular}")
    if caption is not None:
        # Caption is raw LaTeX prose — do not pass through _escape_tex.
        lines.append(rf"  \caption{{{caption}}}")
    if label is not None:
        lines.append(rf"  \label{{{label}}}")
    if caption is not None or label is not None:
        lines.append(r"\end{table}")
    return "\n".join(lines) + "\n"


def _write_triplet(df_csv: pd.DataFrame, df_pretty: pd.DataFrame,
                   base: Path, *, caption: str | None = None,
                   label: str | None = None) -> tuple[Path, Path, Path]:
    """Write a table as CSV (raw), Markdown (pretty), and LaTeX (pretty).

    The raw CSV preserves numeric precision and any 'extras' columns the
    pretty version dropped or merged. The Markdown and LaTeX versions are
    publication-ready: `df_pretty` is expected to contain pre-formatted
    string cells (e.g. "1.89", "[1.86, 1.91]", "7.3e-08"), so we disable
    tabulate's numeric re-parsing to keep them intact.
    """
    base.parent.mkdir(parents=True, exist_ok=True)
    csv_path = base.with_suffix(".csv")
    md_path = base.with_suffix(".md")
    tex_path = base.with_suffix(".tex")
    df_csv.to_csv(csv_path, index=False)
    md_path.write_text(
        df_pretty.to_markdown(index=False, disable_numparse=True) + "\n",
        encoding="utf-8",
    )
    tex_path.write_text(
        _df_to_tex(df_pretty, caption=caption, label=label),
        encoding="utf-8",
    )
    return csv_path, md_path, tex_path


def _order_tokenizers(df: pd.DataFrame, col: str = "tokenizer") -> pd.DataFrame:
    """Re-order rows by TOKENIZER_ORDER, dropping unknown ones to the end."""
    present = [t for t in TOKENIZER_ORDER if t in set(df[col])]
    extras = [t for t in df[col] if t not in TOKENIZER_ORDER]
    cat = pd.Categorical(df[col], categories=present + extras, ordered=True)
    return df.assign(**{col: cat}).sort_values(col).reset_index(drop=True)


# ----------------------------------------------------------------------
# Asset builders
# ----------------------------------------------------------------------

def build_fig1_and_table1(audit: pd.DataFrame, out: Path) -> list[Path]:
    """Figure 1 + Table 1 + Appendix full-audit table (shared input)."""
    written: list[Path] = []
    df = _order_tokenizers(audit.copy())

    # ------ Figure 1 ----------------------------------------------------
    fig, ax = plt.subplots(figsize=(6.4, 3.6))
    x = np.arange(len(df))
    yerr = None
    if {"TP_ci_low", "TP_ci_high"}.issubset(df.columns):
        lower = (df["mean_TP"] - df["TP_ci_low"]).clip(lower=0).values
        upper = (df["TP_ci_high"] - df["mean_TP"]).clip(lower=0).values
        yerr = np.vstack([lower, upper])
    bars = ax.bar(
        x, df["mean_TP"].values,
        yerr=yerr, capsize=3,
        color="#cccccc", edgecolor="black", linewidth=0.8,
    )
    # Highlight bars by parity status without abandoning grayscale-friendliness.
    for bar, tp in zip(bars, df["mean_TP"].values):
        if tp > 1.10:
            bar.set_hatch("///")
        elif tp < 0.90:
            bar.set_hatch("...")
    ax.axhline(1.0, linestyle="--", color="black", linewidth=0.9, zorder=0)
    ax.set_xticks(x)
    ax.set_xticklabels([TOKENIZER_LABELS.get(t, t) for t in df["tokenizer"]],
                       rotation=20, ha="right")
    ax.set_ylabel("Mean tokenization parity (ZH / EN)")
    ax.set_ylim(0, max(2.1, float(df["mean_TP"].max()) * 1.1))
    written.extend(save_figure(fig, out / "fig1_tokenization_parity_by_tokenizer"))

    # ------ Table 1 (main) ---------------------------------------------
    main = df[["tokenizer", "mean_TP", "TP_ci_low", "TP_ci_high",
               "mean_en_tokens", "mean_zh_tokens"]].copy()
    raw = main.copy()
    raw[["mean_TP", "TP_ci_low", "TP_ci_high"]] = raw[
        ["mean_TP", "TP_ci_low", "TP_ci_high"]
    ].round(3)
    raw[["mean_en_tokens", "mean_zh_tokens"]] = raw[
        ["mean_en_tokens", "mean_zh_tokens"]
    ].round(2)

    pretty = pd.DataFrame({
        "Tokenizer": [TOKENIZER_LABELS.get(t, t) for t in main["tokenizer"]],
        "Mean TP": [f"{v:.2f}" for v in main["mean_TP"]],
        "95% CI": [_fmt_ci(lo, hi) for lo, hi in
                   zip(main["TP_ci_low"], main["TP_ci_high"])],
        "Mean EN tokens": [f"{v:.1f}" for v in main["mean_en_tokens"]],
        "Mean ZH tokens": [f"{v:.1f}" for v in main["mean_zh_tokens"]],
    })
    written.extend(_write_triplet(
        raw, pretty, out / "table1_tokenization_audit_summary",
        caption="Tokenization audit summary on FLORES-200 EN-ZH devtest "
                "(N = 1012 paired sentences). TP = mean ZH tokens / EN tokens; "
                "95\\% CI from a paired bootstrap with 1000 resamples.",
        label="tab:audit-main",
    ))

    # ------ Appendix table J (full audit) ------------------------------
    full_cols = ["tokenizer", "mean_TP", "TP_ci_low", "TP_ci_high",
                 "mean_context_shrinkage", "mean_en_tokens", "mean_zh_tokens",
                 "wilcoxon_pvalue"]
    missing = [c for c in full_cols if c not in df.columns]
    if missing:
        raise KeyError(f"summary_by_tokenizer.csv missing expected columns: {missing}")
    full = df[full_cols].copy()
    full_raw = full.copy()
    full_raw[["mean_TP", "TP_ci_low", "TP_ci_high",
              "mean_context_shrinkage"]] = full_raw[
        ["mean_TP", "TP_ci_low", "TP_ci_high", "mean_context_shrinkage"]
    ].round(3)
    full_raw[["mean_en_tokens", "mean_zh_tokens"]] = full_raw[
        ["mean_en_tokens", "mean_zh_tokens"]
    ].round(2)
    full_pretty = pd.DataFrame({
        "Tokenizer": [TOKENIZER_LABELS.get(t, t) for t in full["tokenizer"]],
        "Mean TP": [f"{v:.2f}" for v in full["mean_TP"]],
        "95% CI": [_fmt_ci(lo, hi) for lo, hi in
                   zip(full["TP_ci_low"], full["TP_ci_high"])],
        "Context shrinkage": [f"{v:+.2f}" for v in full["mean_context_shrinkage"]],
        "Mean EN tokens": [f"{v:.1f}" for v in full["mean_en_tokens"]],
        "Mean ZH tokens": [f"{v:.1f}" for v in full["mean_zh_tokens"]],
        "Wilcoxon p": [_fmt_p(p) for p in full["wilcoxon_pvalue"]],
    })
    written.extend(_write_triplet(
        full_raw, full_pretty, out / "appendix_table_full_audit_with_controls",
        caption="Full per-tokenizer audit including context-shrinkage "
                "(1 - 1/TP) and Wilcoxon signed-rank p-values testing "
                "EN-vs-ZH token-count equality within each tokenizer.",
        label="tab:audit-full",
    ))
    return written


def build_fig2_and_appendix_fc(fc: pd.DataFrame, out: Path) -> list[Path]:
    """Figure 2 (examples-fit), appendix figure (accuracy), appendix table."""
    written: list[Path] = []
    needed = {"language", "budget", "examples_fit_mean", "accuracy",
              "cost_per_correct", "n_queries", "tokens_in", "tokens_out"}
    missing = needed.difference(fc.columns)
    if missing:
        raise KeyError(f"fixed_context summary.csv missing columns: {sorted(missing)}")

    pivot_fit = fc.pivot_table(index="budget", columns="language",
                               values="examples_fit_mean", aggfunc="mean").sort_index()
    pivot_acc = fc.pivot_table(index="budget", columns="language",
                               values="accuracy", aggfunc="mean").sort_index()

    # ------ Figure 2 ----------------------------------------------------
    fig, ax = plt.subplots(figsize=(5.6, 3.6))
    for lang in ("en", "zh"):
        if lang not in pivot_fit.columns:
            continue
        st = LANG_STYLE[lang]
        ax.plot(pivot_fit.index, pivot_fit[lang],
                marker=st["marker"], linestyle=st["linestyle"],
                color=st["color"], label=st["label"])
    ax.set_xlabel("Token budget")
    ax.set_ylabel("Mean few-shot demonstrations fit")
    ax.set_xticks(sorted(pivot_fit.index.unique()))
    ax.legend(loc="best")
    written.extend(save_figure(fig, out / "fig2_examples_fit_vs_budget"))

    # ------ Appendix figure G (accuracy) -------------------------------
    fig, ax = plt.subplots(figsize=(5.6, 3.6))
    for lang in ("en", "zh"):
        if lang not in pivot_acc.columns:
            continue
        st = LANG_STYLE[lang]
        ax.plot(pivot_acc.index, pivot_acc[lang],
                marker=st["marker"], linestyle=st["linestyle"],
                color=st["color"], label=st["label"])
    ax.set_xlabel("Token budget")
    ax.set_ylabel("Accuracy")
    ax.set_xticks(sorted(pivot_acc.index.unique()))
    ax.set_ylim(0.0, 1.0)
    ax.legend(loc="best")
    written.extend(save_figure(fig, out / "appendix_fig_accuracy_vs_budget"))

    # ------ Appendix table F -------------------------------------------
    cols = ["language", "budget", "examples_fit_mean", "accuracy",
            "cost_per_correct", "n_queries", "tokens_in", "tokens_out"]
    raw = fc[cols].copy().sort_values(["language", "budget"]).reset_index(drop=True)
    # Round only columns that look good at 3-decimals precision; leave
    # cost_per_correct alone because it is typically O(1e-5) and would round to 0.
    raw[["examples_fit_mean", "accuracy"]] = raw[
        ["examples_fit_mean", "accuracy"]
    ].round(3)
    pretty = pd.DataFrame({
        "Language": ["English" if l == "en" else "Chinese" for l in raw["language"]],
        "Budget": raw["budget"].astype(int),
        "Demos fit (mean)": [f"{v:.1f}" for v in raw["examples_fit_mean"]],
        "Accuracy": [f"{v:.3f}" for v in raw["accuracy"]],
        "Cost per correct (USD)": [
            "n/a" if pd.isna(v) else (f"{v:.6f}" if v >= 1e-4 else f"{v:.2e}")
            for v in raw["cost_per_correct"]
        ],
        "n queries": raw["n_queries"].astype(int),
        "Tokens in": raw["tokens_in"].astype(int),
        "Tokens out": raw["tokens_out"].astype(int),
    })
    written.extend(_write_triplet(
        raw, pretty, out / "appendix_table_fixed_context_full",
        caption="Full Experiment 2 (fixed-context) summary across token budgets "
                "and languages on XNLI few-shot prompts.",
        label="tab:fc-full",
    ))
    return written


def build_table2_radical(cont: pd.DataFrame, coef: pd.DataFrame, out: Path) -> list[Path]:
    """Table 2: compact radical/token sensitivity summary + appendix coef table."""
    written: list[Path] = []
    if cont.empty:
        raise ValueError("contingency_same_radical.csv is empty")
    if coef.empty:
        raise ValueError("logit_coefficients.csv is empty")

    c = cont.iloc[0]
    coef_idx = coef.set_index("term")
    same_rad = coef_idx.loc["same_radical"] if "same_radical" in coef_idx.index else None
    same_tok = coef_idx.loc["same_token"] if "same_token" in coef_idx.index else None
    regularized = bool(coef.get("regularized", pd.Series([False])).any())

    rows = [
        {"Quantity": "P(predicted similar | same radical)",
         "Estimate": f"{c['p_pred_yes_given_same_radical']:.3f}",
         "Detail": f"n={int(c['n_same_radical'])}"},
        {"Quantity": "P(predicted similar | different radical)",
         "Estimate": f"{c['p_pred_yes_given_diff_radical']:.3f}",
         "Detail": f"n={int(c['n_diff_radical'])}"},
        {"Quantity": "Odds ratio (same vs different radical)",
         "Estimate": f"{c['odds_ratio_haldane']:.2f}",
         "Detail": "Haldane-Anscombe corrected"},
        {"Quantity": "Fisher exact p",
         "Estimate": _fmt_p(c["fisher_exact_p"]),
         "Detail": "two-sided"},
        {"Quantity": "Logit β(same_radical)",
         "Estimate": "n/a" if same_rad is None else f"{same_rad['coef']:+.2f}",
         "Detail": "n/a" if same_rad is None else
                   ("regularized (no p)" if bool(same_rad.get("regularized", False))
                    else f"p = {_fmt_p(same_rad['p_value'])}")},
        {"Quantity": "Logit β(same_token)",
         "Estimate": "n/a" if same_tok is None else f"{same_tok['coef']:+.2f}",
         "Detail": "n/a" if same_tok is None else
                   ("regularized (no p)" if bool(same_tok.get("regularized", False))
                    else f"p = {_fmt_p(same_tok['p_value'])}")},
    ]
    pretty = pd.DataFrame(rows)
    raw = pretty.copy()  # already a tidy summary; same content for CSV
    caption = (
        "Behavioral evidence that token identity modulates the model's "
        "character-similarity judgments after controlling for radical "
        "(script) identity. Logit coefficients use cl100k\\_base as the "
        "reference tokenizer for the same\\_token contrast."
    )
    if regularized:
        caption += " Some coefficients used L2-regularised logistic regression; p-values are unavailable for those rows."
    written.extend(_write_triplet(
        raw, pretty, out / "table2_radical_token_sensitivity_summary",
        caption=caption, label="tab:radical-summary",
    ))

    # Appendix coefficient table — keep full precision for the raw CSV;
    # format strings for the pretty rendering. Rounding p-values before
    # formatting would round tiny ones (e.g. 4.8e-06) down to 0.
    coef_raw = coef.copy()
    coef_pretty = pd.DataFrame({
        "Term": coef_raw["term"],
        "β (coef)": [f"{v:+.3f}" for v in coef_raw["coef"]],
        "p value": [_fmt_p(p) for p in coef_raw["p_value"]],
        "Regularized": ["yes" if bool(r) else "no" for r in coef_raw["regularized"]],
    })
    written.extend(_write_triplet(
        coef_raw, coef_pretty, out / "appendix_table_radical_logit_coefficients",
        caption="Full logistic-regression coefficients for Experiment 3.",
        label="tab:radical-coefs",
    ))
    return written


def build_fig3_adaptation(adapt: pd.DataFrame, out: Path) -> list[Path]:
    """Figure 3: tokenizer adaptation counterfactual."""
    needed = {"added_tokens", "mean_TP"}
    missing = needed.difference(adapt.columns)
    if missing:
        raise KeyError(f"audit_before_after.csv missing columns: {sorted(missing)}")

    df = (adapt.drop_duplicates(subset=["added_tokens"])
                .sort_values("added_tokens").reset_index(drop=True))

    fig, ax = plt.subplots(figsize=(5.6, 3.6))
    ax.plot(df["added_tokens"], df["mean_TP"],
            marker="o", linestyle="-", color="#1f77b4", linewidth=1.8)
    ax.axhline(1.0, linestyle="--", color="black", linewidth=0.9, zorder=0)
    ax.set_xlabel("Added Chinese vocabulary pieces")
    ax.set_ylabel("Mean tokenization parity (ZH / EN)")
    # Sensible y-range that always shows both the line and the parity reference.
    y_lo = min(0.7, float(df["mean_TP"].min()) * 0.95)
    y_hi = max(1.15, float(df["mean_TP"].max()) * 1.05)
    ax.set_ylim(y_lo, y_hi)
    return list(save_figure(fig, out / "fig3_tokenizer_adaptation_counterfactual"))


def build_perturbation_assets(pt_summary: pd.DataFrame,
                              pt_rows: pd.DataFrame | None,
                              out: Path) -> list[Path]:
    """Appendix table H + appendix figure I."""
    written: list[Path] = []
    needed = {"transform", "mean_stability_exact", "mean_stability_jaccard",
              "mean_delta_tokens", "delta_accuracy"}
    missing = needed.difference(pt_summary.columns)
    if missing:
        raise KeyError(f"paraphrase summary.csv missing columns: {sorted(missing)}")

    raw = pt_summary[list(needed) + (["n"] if "n" in pt_summary.columns else [])].copy()
    raw = raw.sort_values("transform").reset_index(drop=True)
    raw[["mean_stability_exact", "mean_stability_jaccard",
         "mean_delta_tokens", "delta_accuracy"]] = raw[
        ["mean_stability_exact", "mean_stability_jaccard",
         "mean_delta_tokens", "delta_accuracy"]
    ].round(3)
    pretty = pd.DataFrame({
        "Transform": [TRANSFORM_LABELS.get(t, t) for t in raw["transform"]],
        "Stability (exact)": [f"{v:.3f}" for v in raw["mean_stability_exact"]],
        "Stability (Jaccard)": [f"{v:.3f}" for v in raw["mean_stability_jaccard"]],
        "Δ tokens": [f"{v:+.2f}" for v in raw["mean_delta_tokens"]],
        "Δ accuracy": [f"{v:+.3f}" for v in raw["delta_accuracy"]],
    })
    written.extend(_write_triplet(
        raw, pretty, out / "appendix_table_perturbation_summary",
        caption="Experiment 4: response stability and accuracy delta under "
                "meaning-preserving paraphrases and surface-level token "
                "perturbations. Identity-row stability is the temperature=0 "
                "non-determinism floor.",
        label="tab:perturb-summary",
    ))

    fig, ax = plt.subplots(figsize=(6.0, 3.6))
    if pt_rows is not None and "stability_jaccard" in pt_rows.columns:
        # Box plot keeps the per-prompt distribution visible.
        order = sorted(pt_rows["transform"].unique(),
                       key=lambda t: list(TRANSFORM_LABELS.keys()).index(t)
                       if t in TRANSFORM_LABELS else 999)
        data = [pt_rows.loc[pt_rows["transform"] == t, "stability_jaccard"].values
                for t in order]
        bp = ax.boxplot(data, tick_labels=[TRANSFORM_LABELS.get(t, t) for t in order],
                        patch_artist=True, widths=0.55)
        for patch in bp["boxes"]:
            patch.set_facecolor("#dddddd")
            patch.set_edgecolor("black")
        for med in bp["medians"]:
            med.set_color("black")
        ax.set_ylabel("Stability (Jaccard)")
    else:
        x = np.arange(len(raw))
        ax.bar(x, raw["mean_stability_jaccard"].values,
               color="#cccccc", edgecolor="black", linewidth=0.8)
        ax.set_xticks(x)
        ax.set_xticklabels([TRANSFORM_LABELS.get(t, t) for t in raw["transform"]],
                           rotation=20, ha="right")
        ax.set_ylabel("Mean stability (Jaccard)")
    ax.set_ylim(0.0, 1.05)
    plt.setp(ax.get_xticklabels(), rotation=20, ha="right")
    written.extend(save_figure(fig, out / "appendix_fig_perturbation_stability"))
    return written


# ----------------------------------------------------------------------
# Captions and README
# ----------------------------------------------------------------------

CAPTIONS_MD = """\
# Caption drafts for `reports/paper_assets/`

These are sober, paste-ready first-draft captions for each figure and table.
Adjust to match your manuscript's prose style; the numerical claims should be
left intact unless the underlying CSVs change.

## Main text

### Figure 1 — `fig1_tokenization_parity_by_tokenizer.{png,pdf}`
Mean tokenization parity (ZH / EN) on FLORES-200 EN-ZH devtest (N = 1012),
broken out by tokenizer. The dashed line marks parity (TP = 1.0); error bars
show 95% paired-bootstrap confidence intervals. Chinese incurs a much larger
token burden under `cl100k_base` than under `o200k_base`, Llama 3, or
Qwen 2.5 — a tokenizer-dependent gap, not a property of the language itself.
Hatched bars highlight tokenizers that deviate noticeably above (`///`) or
below (`...`) parity.

### Table 1 — `table1_tokenization_audit_summary.{csv,md,tex}`
Per-tokenizer summary on FLORES-200 EN-ZH devtest: mean tokenization parity
(ZH / EN) with 95% paired-bootstrap CI, and mean token counts per language.
Statistical extras (Wilcoxon, context shrinkage) are deferred to the
appendix table.

### Figure 2 — `fig2_examples_fit_vs_budget.{png,pdf}`
Mean number of few-shot demonstrations that fit inside a fixed token budget
on XNLI, by language. At every shared budget the Chinese prompt fits fewer
demonstrations than the English one. The figure visualises the *context-budget
consequence* of the parity gap in Figure 1; it is not an accuracy claim.

### Table 2 — `table2_radical_token_sensitivity_summary.{csv,md,tex}`
Behavioral evidence that token identity modulates the model's
character-similarity judgments. We report the conditional probability that
the model calls a pair "similar" given same vs. different radical, the
Haldane-Anscombe-corrected odds ratio with Fisher's exact p-value, and
logit coefficients from a regression that controls for radical when
estimating the token-identity effect. Coefficients are behavioral
estimates: they describe input/output regularities, not internal model
representations. Token-identity is computed against `cl100k_base` because
single Han characters fragment into byte tokens under that vocabulary.

### Figure 3 — `fig3_tokenizer_adaptation_counterfactual.{png,pdf}`
Simulated counterfactual audit: mean tokenization parity (ZH / EN) on the
same FLORES-200 corpus after extending the base tokenizer's vocabulary with
0, 1k, and ~5k mined Han n-grams. The dashed line marks parity. This is a
*lightweight, simulated* intervention — we recompute token counts under the
extended vocabulary; we do not retrain or fine-tune the model. The purpose
is to bound how much of the disparity is interface-modifiable.

## Appendix

### Appendix Figure G — `appendix_fig_accuracy_vs_budget.{png,pdf}`
XNLI accuracy at fixed token budgets, by language. Within-row differences
are within Wilson-interval noise for n = 50; we report this for completeness.

### Appendix Table F — `appendix_table_fixed_context_full.{csv,md,tex}`
Full Experiment 2 summary including demonstrations fit, accuracy, cost per
correct prediction, query count, and total in/out tokens for every
(language, budget) cell.

### Appendix Table H — `appendix_table_perturbation_summary.{csv,md,tex}`
Per-transform summary of Experiment 4. The `identity` row is the
temperature = 0 non-determinism floor and should be read as a baseline
against which other rows are interpreted. Δaccuracy ≈ 0 is expected on this
prompt set (the gold answer is preserved by every transform); the
informative quantity is *output stability*.

### Appendix Figure I — `appendix_fig_perturbation_stability.{png,pdf}`
Per-prompt response stability (Jaccard) by transform. Box plots when the
row-level perturbation log is available; bar of means otherwise.

### Appendix Table J — `appendix_table_full_audit_with_controls.{csv,md,tex}`
Full per-tokenizer audit including context shrinkage (1 - 1/TP) and Wilcoxon
signed-rank p-values testing EN-vs-ZH token-count equality within each
tokenizer.

### Appendix Table — `appendix_table_radical_logit_coefficients.{csv,md,tex}`
Raw logistic-regression coefficients for Experiment 3.

## Cautionary notes for all assets

- These are claims about specific tokenizers, models, tasks, and prompt
  formats. They are not claims about the relative difficulty of any human
  language or about model capability in general.
- Closed-vocabulary closed-model results conflate tokenizer, training mix,
  and post-training; the open-model audit (Llama 3, Qwen 2.5) isolates the
  tokenizer axis but not the others.
- Experiment 5's "added tokens" are a counterfactual measurement (we
  recompute token counts), not a fully retrained adapted model.
"""

README_MD = """\
# `reports/paper_assets/` — paper-ready figures and tables

Everything in this directory is regenerated deterministically by

```
python -m src.build_paper_assets
```

from the cached experiment CSVs. The build script never re-runs an
experiment and never makes a network call.

## Inputs

| Asset | Cached input(s) |
|---|---|
| Figure 1 / Table 1 / Appendix Table J | `results/tokenization_audit/summary_by_tokenizer.csv` |
| Figure 2 / Appendix Figure G / Appendix Table F | `results/fixed_context/summary.csv` |
| Table 2 / Appendix coefficient table | `results/radical_sensitivity/contingency_same_radical.csv`, `results/radical_sensitivity/logit_coefficients.csv` |
| Figure 3 | `results/tokenizer_adaptation/audit_before_after.csv` |
| Appendix Table H / Appendix Figure I | `results/paraphrase_token_perturb/summary.csv`, optional row-level `perturbations.csv` |

If any required input is missing, the build fails loudly with the expected
path printed in the error message. Re-run the corresponding experiment
(see the top-level `README.md`) before retrying.

## Outputs

Every figure is written as both `.png` (220 dpi) and `.pdf`. Every table is
written as `.csv` (raw numerical), `.md` (publication-readable), and `.tex`
(simple `tabular` for paste-into-paper).

See `captions.md` for first-draft caption text for each asset.

## Assumptions and fallbacks

- Tokenizer ordering follows the worst-parity-rightward convention:
  `char, byte, qwen25, tiktoken_o200k, llama3, tiktoken_cl100k`. Missing
  tokenizers are dropped silently; unknown ones are appended at the end.
- The perturbation appendix figure prefers `perturbations.csv` (row-level,
  shown as box plots). If that file is absent, it falls back to a bar chart
  of summary means.
- Coefficients flagged as `regularized` in `logit_coefficients.csv` are
  rendered without p-values (none are estimable from a regularised fit) and
  Table 2's caption is amended to note the fallback.
"""


# ----------------------------------------------------------------------
# CLI
# ----------------------------------------------------------------------

@click.command()
@click.option("--results-dir", default="results", type=click.Path(file_okay=False),
              help="Directory containing cached experiment outputs.")
@click.option("--out", "out_dir", default="reports/paper_assets",
              type=click.Path(file_okay=False),
              help="Where to write paper-ready assets.")
def main(results_dir: str, out_dir: str) -> None:
    apply_style()
    root = Path(results_dir)
    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)

    audit = _require_csv(root / "tokenization_audit" / "summary_by_tokenizer.csv")
    fc = _require_csv(root / "fixed_context" / "summary.csv")
    cont = _require_csv(root / "radical_sensitivity" / "contingency_same_radical.csv")
    coef = _require_csv(root / "radical_sensitivity" / "logit_coefficients.csv")
    adapt = _require_csv(root / "tokenizer_adaptation" / "audit_before_after.csv")
    pt_summary = _require_csv(root / "paraphrase_token_perturb" / "summary.csv")
    pt_rows_path = root / "paraphrase_token_perturb" / "perturbations.csv"
    pt_rows = pd.read_csv(pt_rows_path) if pt_rows_path.exists() else None

    written: list[Path] = []
    written.extend(build_fig1_and_table1(audit, out))
    written.extend(build_fig2_and_appendix_fc(fc, out))
    written.extend(build_table2_radical(cont, coef, out))
    written.extend(build_fig3_adaptation(adapt, out))
    written.extend(build_perturbation_assets(pt_summary, pt_rows, out))

    captions_path = out / "captions.md"
    captions_path.write_text(CAPTIONS_MD, encoding="utf-8")
    written.append(captions_path)

    readme_path = out / "README.md"
    readme_path.write_text(README_MD, encoding="utf-8")
    written.append(readme_path)

    click.echo(f"Wrote {len(written)} files to {out.resolve()}:")
    for p in sorted(written):
        click.echo(f"  {p.relative_to(out.parent.parent) if out.parent.parent in p.parents else p}")


if __name__ == "__main__":
    main()
